### ISSUE TITLE
Release new version for Safe v1 compatibility

### ISSUE THREAD

**Issue by vhenzl** [simPod/GraphQL-Utils#22]
I can see that `thecodingmachine/safe` has already been upgraded to v1 on master (de1815daed3a8039009c55d794da946f5ee27e1b, 194abf46b4e53f8518272a28e7e6fb0c6469abf9). Can you please release new version so that `simpod/graphql-utils`  is compatible with Save v1? Thanks.

**Comment by simPod** [comment]
Sure! Will do today or tomorrow. Have one more thing in my mind I wanted to
add.

**Comment by simPod** [comment]
Released https://github.com/simPod/GraphQL-Utils/releases/tag/v0.4.0
