### ISSUE TITLE
Default field resolver per type

### ISSUE THREAD

**Issue by felipevolpatto** [simPod/GraphQL-Utils#4]
Sometimes it might be convenient to set default field resolver per type. Webonyx [implements it](https://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver-per-type) like a charm

What do you think? Should I submit a PR?

**Comment by simPod** [comment]
This library provides suitable abstraction for something of that kind, I guess.

Can you further elaborate the design you have in mind?

**Comment by simPod** [comment]
Ah, option for `resolveField` is missing here, is that it?

**Comment by felipevolpatto** [comment]
> Ah, option for `resolveField` is missing here, is that it?

Yes! The implementation would probably be similar to `setResolver` you have on [FieldBuilder](https://github.com/simPod/GraphQL-Utils/blob/master/src/Builder/FieldBuilder.php).

**Comment by simPod** [comment]
Yes, that would me sense, I'd accept PR like that.
